### ISSUE TITLE
Breaking ABI change in sqlite-net-pcl v1.6.292

### ISSUE THREAD

**Issue by jochembroekhoff** [jamesmontemagno/monkey-cache#73]
In the v1.6.292 release of sqlite-net-pcl, one of the SQLiteConnection constructor's signatures got changed. This happened to be the constructor that MonkeyCache.SQLite.Barrel was using.

This commit shows the change: https://github.com/praeclarum/sqlite-net/commit/8649a689dba1cf5a770f5d853257ff8f76d0db3f.

Since the current release of the application is built agains v1.5, having the newer version of sqlite-net-pcl installed (which is allowed by the dependency constraints), it crashes with a System.MissingMethodException.

**Comment by jamesmontemagno** [comment]
@praeclarum I should just update this? Reason for the break without a bump to 2.0?

**Comment by jamesmontemagno** [comment]
pushing a new preview that will be built against 1.6.x of sql

**Comment by AceOfSpades29** [comment]
Have this been released yet? I'm running into the same issue. I see on the [release pipeline ](https://dev.azure.com/jamesmontemagno/MonkeyCache/_releaseProgress?_a=release-pipeline-progress&releaseId=112)that the nuget prod was rejected due to a timeout. Doesn't appear to have any activity since then.

**Comment by jamesmontemagno** [comment]
1.4.0-beta has this in it
